version: '3.9'

services:
    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    web:
        build: .
        command: python /usr/src/dm_rest/manage.py
        volumes:
            - .:/usr/src/dm_rest
        ports:
            - 8000:8000
        depends_on:
            - db
volumes:
    postgres_data: