version: '3.9'

# Вынести пароли в  .env

services:
    redis:
        image: redis:7.0.4-bullseye
        container_name: redis
        restart: always

    postgres_db:
        image: postgres:14.4-bullseye
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /home/ubuntu/postgres/data
            POSTGRES_INITDB_ARGS: "-A md5"
        ports:
            - "5432:5432"
        # volumes:
        #     - postgres_data:/var/lib/postgresql/data

    django:
        container_name: django
        restart: always
        build:
            context: ./app
        ports:
            - 8000:8000
        command: [ "python", "./src/manage.py", "runserver", "0.0.0.0:8000"]
        # command: bash -c "python ./src/manage.py migrate --noinput && 
        #     python ./src/manage.py runserver 0.0.0.0:8000"
        # volumes:
        #     - ./db:/app/src/db
        depends_on:
            - postgres_db

    worker:
        container_name: worker
        restart: always
        build:
            context: ./app
        volumes:
            - ./cats:/app/src/cats
        command: ['celery', '--workdir=./src', '-A', 'proj', 'worker' ]

    # celery-beats:
    #     container_name: celery-beats
    #     restart: always
    #     build: 
    #         context: ./app
    #     # volumes: 
    #     #     - ./db:/app/src/db
    #     command: ['celery', '--workdir=./src', '-A', 'proj', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']

# volumes:
#     postgres_data: